### ISSUE TITLE
Should delay turning off projector for a few minutes after screen saver kick in.

### ISSUE THREAD

**Issue by petterreinholdtsen** [fredrik-eriksson/kodi_projcontrol#12]
At the moment, the projector is turned off the second the screen saver kick in.  This causes problems with my InFocus projector, which can not be turned on again before it had some time to cool down.  This make it impossible to quickly recover from the screen saver kicking in while I still want to use the system.

It would be better if the projector would turn itself off 1-2 minutes after the screen saver kick in.

**Comment by fredrik-eriksson** [comment]
An option to wait a defined number of seconds after the screensaver activates before shutting down the projector is probably a good idea. We could also do an option to not attempt to start the projector again before a number of seconds has passed, to prevent it getting "stuck" in off-state. Should be possible using some timer and queue logic I think.

**Comment by fredrik-eriksson** [comment]
This is fixed now.
