### ISSUE TITLE
Better naming of po files?

### ISSUE THREAD

**Issue by petterreinholdtsen** [fredrik-eriksson/kodi_projcontrol#16]
From IRC:

<pere> feffe: btw, is the resources/language/English/strings.po directory structure required in kodi?  it is quite unlike what I have seen in other free software projects.
<TeamKodi> [rechi] resources/language/ path is hardcoded in Kodi
<TeamKodi> [rechi] rename English directory to resource.language.en_gb (just a folder with the language name is deprecated)
<pere> will it work with simply resources/language/en.po and resources/language/sv.po ?
<pere> I fail to see the point of having a directory with only one file in it...
<TeamKodi> [rechi] no that doesn't work
<TeamKodi> resources/language/resource.language.en_gb/strings.po is the correct path
<pere> why en_gb instead of only en?
<TeamKodi> [rechi] language_region
<TeamKodi> eg en_us is a different language
<pere> actually, it is language_country, and I am asking if Kodi is smart enough to handle only language, or if it believe all languages are country specific.  In other words, is it following RFC 3066 or did it make up its own scheme?

[Did not get a reply to the last one before I went to bed. :)]

**Comment by fredrik-eriksson** [comment]
fixed!
