### ISSUE TITLE
NameError: global name 'monitor' is not defined

### ISSUE THREAD

**Issue by petterreinholdtsen** [fredrik-eriksson/kodi_projcontrol#19]
I just noticed this message in my /storage/.kodi/temp/kodi.log:

```
08:21:40.154 T:1744417696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'monitor' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.projcontrol/lib/monitor.py", line 72, in onScreensaverDeactivated
                                                monitor.waitForAbort((min_turnaround-time_since_stop.seconds)*1000)
                                            NameError: global name 'monitor' is not defined
                                            -->End of Python script error report<--
```

**Comment by petterreinholdtsen** [comment]
Looking at the code, it seem to me the waitForAbort() method is simply not implemented.  Did it change name?  It is used twice in the code.

**Comment by fredrik-eriksson** [comment]
It's a method from the superclass xbmc.Monitor, so correct call should be to self.waitForAbort(). This is probably caused by a bad copy-paste from my side. Could you try the fix to make sure it looks fine for you before I tag a new release?

**Comment by petterreinholdtsen** [comment]
[Fredrik Eriksson]
> It's a method from the superclass xbmc.Monitor, so correct call should
> be to self.waitForAbort(). This is probably caused by a bad copy-paste
> from my side. Could you try the fix to make sure it looks fine for you
> before I tag a new release?

Replacing monitor with self got rid of the exception error, but the
projector did not start after the required waiting period, and the
"Screensaver deactivated too soon, will sleep a while before starting
projector" message did not show up in /storage/.kodi/temp/kodi.log (but
that might be because debugging is not enabled).

So a step forward, but I suspect something is still not working as it
should.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by fredrik-eriksson** [comment]
OK, next attempt, previously I used sleep there, which took milliseconds as argument, but waitForAbort() takes seconds, so the timeout got quite long :)

could you see if this works better?

**Comment by petterreinholdtsen** [comment]
[Fredrik Eriksson]
> OK, next attempt, previously I used sleep there, which took
> milliseconds as argument, but waitForAbort() takes seconds, so the
> timeout got quite long :)
>
> could you see if this works better?

Definitely better.

This time I enabled debugging, to have a better idea what is going on,
and this is what I could see.  First, when the screensaver kick in:

23:05:26.386 T:1735877536   DEBUG: projcontrol: Screensaver activated, scheduling projector shutdown
23:05:26.716 T:1859122080   DEBUG: projcontrol: projector responded: '(LMP?)(0-65535,1886)'
23:05:26.716 T:1859122080   DEBUG: projcontrol: Command sent successfully!
23:05:26.716 T:1859122080   DEBUG: projcontrol: sending command '(PWR0)'
23:05:26.817 T:1859122080   DEBUG: projcontrol: projector responded: '(PWR0)'
23:05:26.817 T:1859122080   DEBUG: projcontrol: Command sent successfully!
23:05:26.817 T:1859122080   DEBUG: projcontrol: send_command returned None
23:05:26.963 T:1859122080   DEBUG: projcontrol: do_cmd returns: None

Next, I press a few arrow keys to try to activate kodi and the
projector:

23:05:38.247 T:1735877536   DEBUG: projcontrol: Screensaver deactivated, aborting any scheduled projector shutdown
23:05:38.247 T:1735877536   DEBUG: projcontrol: Screensaver deactivated too soon, will sleep a while before starting projector

Next, it seem to try to turn off the projector again, but it is already
turned off and this have no effect.

23:06:42.305 T:1735877536   DEBUG: projcontrol: Screensaver activated, scheduling projector shutdown
23:06:42.407 T:1727488928   DEBUG: projcontrol: projector responded: '(LMP?)(0-65535,1886)'
23:06:42.407 T:1727488928   DEBUG: projcontrol: Command sent successfully!
23:06:42.407 T:1727488928   DEBUG: projcontrol: sending command '(PWR0)'
23:06:42.468 T:1727488928   DEBUG: projcontrol: projector responded: '(PWR0)'
23:06:42.468 T:1727488928   DEBUG: projcontrol: Command sent successfully!
23:06:42.468 T:1727488928   DEBUG: projcontrol: send_command returned None
23:06:42.721 T:1727488928   DEBUG: projcontrol: do_cmd returns: None

At last it turn on the projector again:

23:06:57.247 T:1735877536   DEBUG: projcontrol: Screensaver deactivated, starting projector
23:06:57.275 T:1735877536   DEBUG: projcontrol: projector responded: '(LMP?)(0-65535,1886)'
23:06:57.276 T:1735877536   DEBUG: projcontrol: Command sent successfully!
23:06:57.276 T:1735877536   DEBUG: projcontrol: sending command '(PWR1)'
23:06:57.289 T:1735877536   DEBUG: projcontrol: projector responded: '(PWR1)'
23:06:57.289 T:1735877536   DEBUG: projcontrol: Command sent successfully!
23:06:57.289 T:1735877536   DEBUG: projcontrol: send_command returned None
23:06:57.426 T:1735877536   DEBUG: projcontrol: do_cmd returns: None

I did not use the GUI and left the screen saver to kick in, and a bit
later, it turn if off again:

23:07:17.229 T:1735877536   DEBUG: projcontrol: Screensaver deactivated, aborting any scheduled projector shutdown
23:07:17.230 T:1735877536   DEBUG: projcontrol: Screensaver deactivated too soon, will sleep a while before starting projector

It look like the screen saver trigger a projector poweroff while it is
still off, waiting to be turned on again.  Perhaps the code should query
the projector to see if it is on or off?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by fredrik-eriksson** [comment]
I think you set your screensaver to activate after 1 minute while the backoff timer for the projector is longer than that. I don't think it's a problem that it wants to shut down the projector while it's already off, but if there is a projector which may take harm from that I will have to fix it later :)

One thing that could be done is to deactivate the screensaver if it's running when the projector is starting. That way, if the screensaver has kicked in while waiting for the projector to be ready to start, you still get the expected result: The projector starts after you have done something to deactivate the screensaver, and the kodi idle time starts counting from when the projector has started and you can actually use the UI again. Perhaps I'll look into that.

**Comment by petterreinholdtsen** [comment]
[Fredrik Eriksson]
> I think you set your screensaver to activate after 1 minute while the
> backoff timer for the projector is longer than that. I don't think
> it's a problem that it wants to shut down the projector while it's
> already off, but if there is a projector which may take harm from that
> I will have to fix it later :)

I agree it isn't a problem.  I just believe the code could be smarter,
and check what the status of the projector is before trying to change
it.  This would allow it to detect when I manually turn on the
projector. :)

I'll increase the screensaver activation value to try to avoid the
problem on my end.

> One thing that could be done is to deactivate the screensaver if it's
> running when the projector is starting. That way, if the screensaver
> has kicked in while waiting for the projector to be ready to start,
> you still get the expected result: The projector starts after you have
> done something to deactivate the screensaver, and the kodi idle time
> starts counting from when the projector has started and you can
> actually use the UI again. Perhaps I'll look into that.

That sound like a good approach.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Is this issue perhaps solved now?
