### ISSUE TITLE
Adding add-on to official repository?

### ISSUE THREAD

**Issue by petterreinholdtsen** [fredrik-eriksson/kodi_projcontrol#2]
I'm unable to find this add-on in the official repositories.  Would you consider adding it there, to make it easier to install for the untrained user?

I searched for it using <URL: https://kodi.tv/addons/browse?keyword=epson&category=All&author=&sort=title+ASC >.

**Comment by fredrik-eriksson** [comment]
There are a few reasons why I have not published it in the official repositories, but basically it cooks down to that I don't think the average user would find it very useful. Also I'm pretty sure the kodi people doesn't like that it requires that flask is installed manually. That said, if we add support for one or two more projectors and figure out what to do with the flask dependency, then maybe it could be fun to add it to the official repository.
