### ISSUE TITLE
Device Support Request - Acer V7500

### ISSUE THREAD

**Issue by h0n2a** [fredrik-eriksson/kodi_projcontrol#22]
Hi,

thanks for the plugin, it seems to be someting I was looking for.
Is possible to add support for Acer V7500 projector?
The RS232 protocol is here:
https://global-download.acer.com/GDFiles/Document/User%20Manual/User%20Manual_Acer_1.0_A_A.xls?acerid=636409803890749228

Thanks!

**Comment by fredrik-eriksson** [comment]
Hi, thanks for showing interest, it most definitely would be possible to make the plugin support this projector, but I can't really do it without having a projector to test with. This manual is missing some information that is needed for a proper implementation (most notably the syntax of responses and how to know if the projector is ready to receive commands). It is easy enough to figure those things out if you have a projector to test with, but without I can't really know.

If you feel like giving it a try yourself I would recommend trying out the serial commands manually a bit and then make a copy of epson.py and tweak it until it works with your projector. I will gladly merge a PR adding support for additional projectors.
